Update scrape.yml

diff --git a/.github/workflows/scrape.yml b/.github/workflows/scrape.yml
--- a/.github/workflows/scrape.yml
+++ b/.github/workflows/scrape.yml
@@ -1,27 +1,40 @@
+# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
-     branches:
-       - master
-       
-           
+    branches: [main, master]
+  pull_request:
+    branches: [main, master]
+
+name: R-CMD-check
+
 jobs:
-  blogdown: 
-    name: Render-blog
-    runs-on: windows-latest
-    container: docker://dvorg/cml:latest
+  R-CMD-check:
+    runs-on: ubuntu-latest
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+      R_KEEP_PKG_SOURCE: yes
     steps:
+      - uses: actions/checkout@v2
 
+      - uses: r-lib/actions/setup-r@v1
+        with:
+          use-public-rspm: true
 
-      - name: Setup R dependencies
-        run: |
-          R -e 'install.packages("tidyverse")'
-          R -e 'install.packages("rvest")'
-          R -e 'install.packages("magrittr")'
-          R -e 'install.packages("gsheet")'
-          R -e 'install.packages("googlesheets4")'
-          R -e 'install.packages("RSelenium")'
-      - name: Run the script 
-        env: 
-          repo_token: ${{secrets.GITHUB_TOKEN }}
-          run: |
-            Rscript tallinnauhingute_scraper.R
+      - uses: r-lib/actions/setup-r-dependencies@v1
+        with:
+          extra-packages: rcmdcheck
+
+      - uses: r-lib/actions/check-r-package@v1
+
+      - name: Show testthat output
+        if: always()
+        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
+        shell: bash
+
+      - name: Upload check results
+        if: failure()
+        uses: actions/upload-artifact@main
+        with:
+          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
+          path: check
